
export let FORM_ARTICULO = {
    titulo: 'Articulo',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Articulo',
    campos: [
    {
        etiqueta: 'select',
        claseGrid: 'col-lg-2 col-md-3 col-sm-12 col-xs-12',
        nombre: 'Tipo',
        label_i18n: 'tipo',
        placeholder_i18n: 'tipo_articulo',
        requerido: true,
        tipo: 'TipoArticulo',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-5',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Idioma',
        label_i18n: 'idioma_publicacion',
        placeholder_i18n: 'placeholder_idioma_publicacion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Ano',
        label_i18n: 'ano',
        placeholder_i18n: 'ano',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Mes',
        label_i18n: 'mes',
        placeholder_i18n: 'mes',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-3',
        nombre: 'Revista',
        label_i18n: 'revista',
        placeholder_i18n: 'revista',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-1',
        nombre: 'Volumen',
        label_i18n: 'volumen',
        placeholder_i18n: 'volumen',
        requerido: false,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-1',
        nombre: 'Fasciculo',
        label_i18n: 'fasciculo',
        placeholder_i18n: 'fasciculo',
        requerido: false,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-1',
        nombre: 'Serie',
        label_i18n: 'serie',
        placeholder_i18n: 'serie',
        requerido: false,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Ubicacion',
        label_i18n: 'ubicacion',
        placeholder_i18n: 'ubicacion',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-2',
        nombre: 'MedioDivulgacion',
        label_i18n: 'mediodivulgacion',
        placeholder_i18n: 'mediodivulgacion',
        requerido: true,
        tipo: 'MedioDivulgacion',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Url',
        label_i18n: 'url',
        placeholder_i18n: 'url',
        requerido: false,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Doi',
        label_i18n: 'doi',
        placeholder_i18n: 'doi',
        requerido: false,
        tipo: 'text',
    },
    ],
}
