
export let FORM_LIBRO = {
    titulo: 'Libro',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Libro',
    campos: [
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Persona',
    //     label_i18n: 'persona',
    //     placeholder_i18n: 'persona',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'TituloLibro',
        label_i18n: 'titulolibro',
        placeholder_i18n: 'titulolibro',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'select',
        // relacion: false,
        claseGrid: 'col-3',
        nombre: 'TipoPublicacion',
        label_i18n: 'tipopublicacion',
        placeholder_i18n: 'tipopublicacion',
        requerido: true,
        tipo: 'TipoPublicacionLibro',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Ano',
        label_i18n: 'ano',
        placeholder_i18n: 'ano',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-2',
        nombre: 'Mes',
        label_i18n: 'mes',
        placeholder_i18n: 'mes',
        requerido: true,
        tipo: 'number',
        // id: 'Id',
        key: 'Nombre',
        relacion: false,
        opciones: [
            { Id: 1, Nombre: 'Enero'},
            { Id: 2, Nombre: 'Febrero'},
            { Id: 3, Nombre: 'Marzo' },
            { Id: 4, Nombre: 'Abril' },
            { Id: 5, Nombre: 'Mayo' },
            { Id: 6, Nombre: 'Junio' },
            { Id: 7, Nombre: 'Julio' },
            { Id: 8, Nombre: 'Agosto' },
            { Id: 9, Nombre: 'Septiembre|' },
            { Id: 10, Nombre: 'Octubre' },
            { Id: 11, Nombre: 'Noviembre'},
            { Id: 12, Nombre: 'Diciembre' },
        ],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'TituloCapitulo',
        label_i18n: 'titulocapitulo',
        placeholder_i18n: 'titulocapitulo',
        requerido: false,
        tipo: 'text',
        // ng-disabled: 'TipoPublicacion=1',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-1',
        nombre: 'Paginas',
        label_i18n: 'paginas',
        placeholder_i18n: 'paginas',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-2',
        nombre: 'Isbn',
        label_i18n: 'isbn',
        placeholder_i18n: 'isbn',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-3',
        nombre: 'Ubicacion',
        label_i18n: 'ubicacion',
        placeholder_i18n: 'ubicacion',
        requerido: true,
        tipo: 'Lugar',
        key: 'Nombre',
        relacion: false,
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-3',
        nombre: 'MedioDivulgacion',
        label_i18n: 'mediodivulgacion',
        placeholder_i18n: 'mediodivulgacion',
        requerido: true,
        tipo: 'MedioDivulgacion',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-3',
        nombre: 'MedioPublicacion',
        label_i18n: 'mediopublicacion',
        placeholder_i18n: 'mediopublicacion',
        requerido: true,
        tipo: 'MedioPublicacion',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-3',
        nombre: 'Editorial',
        label_i18n: 'editorial',
        placeholder_i18n: 'editorial',
        requerido: true,
        tipo: 'text',
    },
    ],
}
